user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

bt_blog:
    resource: "@BTBlogBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"