bt_blog_home:
    path:     /
    defaults: { _controller: BTBlogBundle:Main:index }

bt_blog_benjamin:
    path:     /benjamin
    defaults: { _controller: BTBlogBundle:Main:benjamin }
bt_blog_add:
    path:     /add
    defaults: { _controller: BTBlogBundle:Main:add }
bt_blog_view:
    path:     /view/{id}
    defaults: { _controller: BTBlogBundle:Main:view }
