bt_blog_home:
    path:     /
    defaults: { _controller: BTBlogBundle:Main:index }

bt_blog_benjamin:
    path:     /benjamin
    defaults: { _controller: BTBlogBundle:Main:benjamin }
bt_blog_thomas:
    path:     /thomas
    defaults: { _controller: BTBlogBundle:Main:thomas }
bt_blog_addCommentary:
    path:     /addCom/{id}
    defaults: { _controller: BTBlogBundle:Main:addCom }
bt_blog_viewArticle:
    path:     /viewArt/{id}
    defaults: {_controller: BTBlogBundle:Main:viewArt}