bt_blog_home:
    path:     /
    defaults: { _controller: BTBlogBundle:Main:index }

bt_blog_benjamin:
    path:     /benjamin
    defaults: { _controller: BTBlogBundle:Main:benjamin }
bt_blog_thomas:
    path:     /thomas
    defaults: { _controller: BTBlogBundle:Main:thomas }
bt_blog_addCommentary:
    path:     /addCom/{id}
    defaults: { _controller: BTBlogBundle:Main:addCom }
bt_blog_rmCommentary:
    path:     /rmCom/{id}
    defaults: { _controller: BTBlogBundle:Main:rmCom }
bt_blog_updCommentary:
    path:     /updCom/{id}/{idPost}
    defaults: { _controller: BTBlogBundle:Main:updCom }
bt_blog_viewArticle:
    path:     /viewArt/{id}
    defaults: {_controller: BTBlogBundle:Main:viewArt}
bt_blog_addArticle:
    path:     /addArt
    defaults: {_controller: BTBlogBundle:Main:addArt}
bt_blog_rmArticle:
    path:     /rmArt/{id}
    defaults: {_controller: BTBlogBundle:Main:rmArt}
bt_blog_updArticle:
    path:     /updArt/{id}
    defaults: {_controller: BTBlogBundle:Main:updArt}
bt_blog_addMedia:
    path:     /addMed/{id}
    defaults: {_controller: BTBlogBundle:Main:addMed}