<?php

namespace BTBlogBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;

/**
 * ArticlesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticlesRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastArticlesPosted($postBy,$limit){                                                                              // Get the last articles from an author


        $qb=$this->createQueryBuilder('a');


        $qb ->setParameter('postBy',$postBy)
            ->where('a.postBy = :postBy')
            ->orderBy('a.date','DESC');


        $qb->setMaxResults($limit);


        return $qb
            ->getQuery()
            ->getResult();

    }


}
